import { readdir } from "node:fs/promises";
import path from "node:path";
import { exists, writeText } from "../lib/fsx";
import { P, ROOT } from "../lib/paths";
import { listBrands } from "../brands/load";
import { listPackageIds } from "../package/load";

/**
 * Generates video/remotion/src/generated/registry.ts with static JSON imports of every
 * content/<id>/video/props*.json, so Studio lists all packages and hot-reloads props edits.
 */
export const registerCompositions = async () => {
  const entries: { id: string; format: string; rel: string }[] = [];
  for (const id of await listPackageIds()) {
    const vdir = path.join(P.pkgDir(id), "video");
    if (!exists(vdir)) continue;
    for (const f of (await readdir(vdir)).filter((n) => /^props(\.[0-9x]+)?\.json$/.test(n)).sort()) {
      const format = f === "props.json" ? "9x16" : f.slice(6, -5);
      entries.push({ id, format, rel: `../../../../content/${id}/video/${f}` });
    }
  }
  const lines = [
    "// GENERATED by `npm run mos -- video register` — do not edit.",
    'import type { VideoProps } from "@mos/core";',
    ...entries.map((e, i) => `import p${i} from "${e.rel}";`),
    "",
    "export const PACKAGES: { id: string; format: string; props: VideoProps }[] = [",
    ...entries.map((e, i) => `  { id: "${e.id}", format: "${e.format}", props: p${i} as VideoProps },`),
    "];",
    "",
  ];
  await writeText(path.join(P.remotion(), "src", "generated", "registry.ts"), lines.join("\n"));
  await registerBrands();
  return entries;
};

/**
 * Generates video/remotion/src/generated/brands.ts: static imports of every brand's tokens.json and
 * brand.json, so Remotion knows each brand's tokens and language without hardcoding brand names.
 */
export const registerBrands = async () => {
  const ids = listBrands();
  const lines = [
    "// GENERATED by `npm run mos -- video register` — do not edit.",
    ...ids.flatMap((id, i) => [`import t${i} from "../../../../brands/${id}/tokens.json";`, `import b${i} from "../../../../brands/${id}/brand.json";`]),
    "",
    "export const BRANDS: Record<string, { tokens: unknown; language: string }> = {",
    ...ids.map((id, i) => `  "${id}": { tokens: t${i}, language: b${i}.language },`),
    "};",
    "",
  ];
  await writeText(path.join(P.remotion(), "src", "generated", "brands.ts"), lines.join("\n"));
  return ids;
};

export const compositionId = (pkgId: string, format: string) => `${pkgId}-${format}`;

export const remotionDir = () => path.join(ROOT, "video", "remotion");
